# -*- coding: utf-8 -*-
"""Sprint2_Modelagem linear

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJTJTzxEpAYoboI9JLUT56VQ3R_aLvox
"""

# SPRINT 2 - Modelagem Linear para Aprendizado de Máquina
# INTEGRANTES : Maria Eduarda Rocha Benjamim; Pedro Henrique Neves(apresentador); Akin Alexandre Mendes Martins**
# TURMA: 1CCPJ

# Importação de biblioteca auxiliar para ciência de dados.

import pandas as pd
import matplotlib.pyplot as plt

# Carregar a base
df = pd.read_csv("/content/charging_ev_and_grid_optimization_dataset (2).csv")

# GRÁFICO DE SETORES

plt.figure(figsize=(8,8))

df["vehicle_type"].value_counts().plot(
      kind="pie",
    autopct="%1.1f%%",
    startangle=90,
    cmap="Pastel1"
)

plt.title("Distribuição dos Tipos de Veículos")
plt.legend(title="Tipo de Veículo")
plt.ylabel("")
plt.show()

# GRÁFIICO DE BARRAS

plt.figure(figsize=(8, 7))

df["weather_condition"].value_counts().plot(
    kind="bar",
    color="skyblue",
    label="Quantidade"
)

plt.title("Condição Climática Registrada")
plt.xlabel("Condição Climática")
plt.ylabel("Frequência")
plt.legend()
plt.show()

# HISTOGRAMA

plt.figure(figsize=(8,5))

plt.hist(
    df["energy_consumed_kWh"],
    bins=20,
    color="green"
)

plt.title("Distribuição do Consumo de Energia")
plt.xlabel("Energia Consumida (kWh)")
plt.ylabel("Frequência")
plt.show()

# BOXPLOT

plt.figure(figsize=(8,5))

plt.boxplot(
    df["charging_duration"],
    patch_artist=True
)

plt.title("Boxplot da Duração do Carregamento")
plt.ylabel("Duração (minutos)")
plt.show()

# ANÁLISE UNVARIADA 1

energia = df["energy_consumed_kWh"]

print("\nANÁLISE - ENERGY CONSUMED")

print("Média:", energia.mean())
print("Mediana:", energia.median())
print("Moda:", energia.mode()[0])

print("Desvio Padrão:", energia.std())
print("Variância:", energia.var())
print("Amplitude:", energia.max() - energia.min())

print("Q1:", energia.quantile(0.25))
print("Q2:", energia.quantile(0.50))
print("Q3:", energia.quantile(0.75))

# ANÁLISE UNVARIADA 2

duracao = df["charging_duration"]

print("\nANÁLISE - CHARGING DURATION")

print("Média:", duracao.mean())
print("Mediana:", duracao.median())
print("Moda:", duracao.mode()[0])

print("Desvio Padrão:", duracao.std())
print("Variância:", duracao.var())
print("Amplitude:", duracao.max() - duracao.min())

print("Q1:", duracao.quantile(0.25))
print("Q2:", duracao.quantile(0.50))
print("Q3:", duracao.quantile(0.75))